# Generated by Django 2.1 on 2020-08-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='images',
            new_name='image',
        ),
    ]
