# Generated by Django 2.1 on 2020-08-07 01:29

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to=organization.models.CourseOrg.upload_to, verbose_name='封面图'),
        ),
    ]
