# Generated by Django 2.1 on 2020-08-07 09:46

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20200807_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to=organization.models.Teacher.upload_to, verbose_name='头像'),
        ),
    ]
