# Generated by Django 2.1 on 2020-08-07 02:01

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200806_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=course.models.Course.upload_to, verbose_name='封面图'),
        ),
    ]
