# Generated by Django 2.1 on 2020-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='...', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='课程须知:', max_length=300, verbose_name='课程须知'),
        ),
    ]
